# Generated by Django 2.0.2 on 2020-01-19 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('ans', models.CharField(default=None, max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('round', models.IntegerField(default=1)),
            ],
        ),
    ]
