# Generated by Django 2.0.2 on 2020-02-03 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_question_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='images'),
        ),
    ]
