# Generated by Django 2.0.2 on 2020-02-05 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20200203_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(default='/media/images/default.png', upload_to='images'),
        ),
    ]
