# Generated by Django 2.2.8 on 2020-01-01 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='score',
            new_name='points',
        ),
        migrations.AddField(
            model_name='profile',
            name='money',
            field=models.IntegerField(default=500),
        ),
    ]
