# Generated by Django 3.0.1 on 2020-01-02 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20200101_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='weapons',
            field=models.TextField(null=True),
        ),
    ]
