# Generated by Django 3.0.1 on 2020-01-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20200102_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='weapons',
            field=models.TextField(null=True),
        ),
    ]
