# Generated by Django 3.0.1 on 2020-01-02 15:18

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20200102_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='flame_thrower',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='flipper',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='machine_gun',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='sledge_hammer',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='spinning_blades',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='water_jet',
        ),
        migrations.AddField(
            model_name='profile',
            name='weapons',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('flame_thrower', 'Flame Thrower'), ('water_jet', 'Water Jet'), ('sledge_hammer', 'Sledge Hammer'), ('spinning_blades', 'Spinning Blades'), ('machine_gun', 'Machine Gun'), ('Flipper', 'Flipper'), ('None', 'None')], default='None', max_length=78),
        ),
    ]
