# Generated by Django 2.2.8 on 2020-01-04 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20200102_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='weapons',
        ),
    ]
