# Generated by Django 2.2.8 on 2020-01-05 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_auto_20200105_0712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderedweapons',
            name='weapons',
        ),
        migrations.AddField(
            model_name='orderedweapons',
            name='weapons',
            field=models.ManyToManyField(to='game.Weapons'),
        ),
    ]
