# Generated by Django 2.2.8 on 2020-01-05 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_auto_20200105_0810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderedweapons',
            name='weapons',
        ),
        migrations.AddField(
            model_name='orderedweapons',
            name='weapons',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.Weapons'),
        ),
    ]
