# Generated by Django 2.2.8 on 2020-01-06 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_auto_20200105_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='weapon_list',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
