# Generated by Django 3.0.1 on 2020-01-06 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_defence_ordereddefence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defence',
            name='points',
        ),
        migrations.AddField(
            model_name='profile',
            name='defence_list',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
