# Generated by Django 3.0.1 on 2020-01-09 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_auto_20200107_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_playing',
            field=models.BooleanField(default=True),
        ),
    ]
