# Generated by Django 2.0.2 on 2020-01-19 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0019_profile4'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='curr_round',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='submit_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
