# Generated by Django 2.0.2 on 2020-01-23 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0022_auto_20200123_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='defence_list',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='weapon_list',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
