# Generated by Django 3.0.1 on 2020-01-30 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0023_auto_20200123_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile1',
            name='curr_round',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='profile2',
            name='curr_round',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='profile3',
            name='curr_round',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='profile4',
            name='curr_round',
            field=models.IntegerField(default=1),
        ),
    ]
