# Generated by Django 3.0.1 on 2020-01-30 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0024_auto_20200124_1657'),
        ('game', '0024_auto_20200130_1705'),
    ]

    operations = [
    ]
