# Generated by Django 3.0.1 on 2020-01-30 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0025_merge_20200130_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile1',
            name='curr_round',
        ),
        migrations.RemoveField(
            model_name='profile2',
            name='curr_round',
        ),
        migrations.RemoveField(
            model_name='profile3',
            name='curr_round',
        ),
        migrations.RemoveField(
            model_name='profile4',
            name='curr_round',
        ),
    ]
